# This is a config for E2B sandbox template.
# You can use template ID (9w7ehqrl9ps0lyaq708s) or template name (-vibe-dev-test-7) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("-vibe-dev-test-7") # Sync sandbox
# sandbox = await AsyncSandbox.create("-vibe-dev-test-7") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('-vibe-dev-test-7')

team_id = "c8f8546e-c19f-4504-9df4-6ef21b4ddc94"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "-vibe-dev-test-7"
template_id = "9w7ehqrl9ps0lyaq708s"
